name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 18
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B clean verify

    - name: Run unit and integration tests
      run: mvn test

    - name: Run web interface tests
      run: mvn -Dtest=ada.edu.demo.webtest.WebInterfaceTests test

    - name: Run functionality tests
      run: mvn -Dtest=ada.edu.demo.webtest.config.FunctionalityTests test
